on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  before_script: chmod 0777 ./node_modules/.bin/mocha

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      
      - name: npm install
        run: npm install 

      - run: npm run test
        
      - name: Coveralls
        uses:  coverallsapp/github-action@master
        with:
          coverage-files: ./././node_modules/coveralls/bin/coveralls.js
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
          coveralls-endpoint: https://coveralls.io
